hr watch all employee data
rorpyll/Employeemanagementsystem pull request #143
Opened 2023-01-11 09:59 UTC by shivamchouhan123

2023-01-11 10:29 UTC, ror-mahesh requested changes

2023-01-11 10:29 UTC, ror-mahesh commented on app/serializer/api/v1/employee_serializer.rb
> +        # if object&.emp_image&.attached?
why you comment this?????

2023-01-11 10:31 UTC, shivamchouhan123 commented on app/serializer/api/v1/employee_serializer.rb
> +        # if object&.emp_image&.attached?
page refresh karo

2023-01-11 10:32 UTC, shivamchouhan123 commented on app/controllers/api/v1/employees_controller.rb
> +          render json: {
show action also use in @employee_data

2023-01-11 10:42 UTC, ror-mahesh commented on app/controllers/api/v1/employees_controller.rb
> +          render json: {
but this is an index action?

2023-01-11 11:32 UTC, ror-mahesh approved these changes
Try to set commit name unique according to your task.

2023-01-11 11:34 UTC, ror-mahesh requested changes

2023-01-11 11:34 UTC, ror-mahesh commented on app/controllers/api/v1/employees_controller.rb
>            data: serializer_data(@employee_data, employee_serializer),
`@employee_data` not define..

2023-01-11 11:34 UTC, ror-mahesh commented on app/controllers/api/v1/employees_controller.rb
> +        if current_employee.is_hr?
what would you return when `current_employee` is not HR?

2023-01-11 11:55 UTC, shivamchouhan123 commented on app/controllers/api/v1/employees_controller.rb
> +        if current_employee.is_hr?
resolve

2023-01-11 11:56 UTC, shivamchouhan123 commented on app/controllers/api/v1/employees_controller.rb
>            data: serializer_data(@employee_data, employee_serializer),
resolve

2023-01-12 05:36 UTC, ror-mahesh approved these changes
LGTM

2023-01-12 05:36 UTC, merged