Create employee
rorpyll/Employeemanagementsystem pull request #148
Opened 2023-01-12 09:48 UTC by shivamchouhan123

2023-01-12 13:04 UTC, ror-mahesh requested changes

2023-01-12 13:04 UTC, ror-mahesh commented on app/controllers/api/v1/employees_controller.rb
> +      skip_before_action :verify_authenticity_token #, only: [:update_password]
why you change this?

2023-01-12 13:04 UTC, ror-mahesh commented on app/controllers/api/v1/employees_controller.rb
> +             render json: {errors: [employee_data.errors.full_messages]}, status: 302, type: 'Found'
is this send proper error messages?

2023-01-12 13:04 UTC, ror-mahesh commented on app/controllers/api/v1/employees_controller.rb
> +        params.require(:employee).permit(:id, :name, :email, :password, :phone_number, :password_confirmation, :role_id, :designation_id,)
where is image attribute?

Are you permitted all attributes of employee?

2023-01-16 10:13 UTC, ror-mahesh requested changes

2023-01-16 10:13 UTC, ror-mahesh commented on app/controllers/api/v1/daily_tasks_controller.rb
> +            data: single_data(employee, daily_task_serializer),
Is This correct way to do this type of tasks?

2023-01-16 11:15 UTC, shivamchouhan123 commented on app/controllers/api/v1/daily_tasks_controller.rb
> +            data: single_data(employee, daily_task_serializer),
resolve

2023-01-16 13:16 UTC, shivamchouhan123 commented on app/controllers/api/v1/daily_tasks_controller.rb
> +            data: single_data(employee, daily_task_serializer),
check

2023-01-16 13:35 UTC, ror-mahesh approved these changes
LGTM

2023-01-16 13:35 UTC, merged