Hr watch leave
rorpyll/Employeemanagementsystem pull request #150
Opened 2023-01-17 06:57 UTC by shivamchouhan123

2023-01-17 12:06 UTC, ror-mahesh requested changes

2023-01-17 12:06 UTC, ror-mahesh commented on app/controllers/api/v1/attendences_controller.rb
> +                              Attendence.all.order(id: :desc)
refactor the code..

2023-01-18 06:33 UTC, shivamchouhan123 commented on app/controllers/api/v1/attendences_controller.rb
> +                              Attendence.all.order(id: :desc)
resolve

2023-01-18 06:33 UTC, shivamchouhan123 commented on app/controllers/api/v1/leafs_controller.rb
> +            render json: {
resolve

2023-01-18 07:29 UTC, ror-mahesh approved these changes
LGTM

2023-01-18 07:29 UTC, merged