EMS106 - HR can show particular employee attendance
rorpyll/Employeemanagementsystem pull request #16
Opened 2022-05-06 11:56 UTC by rorpyll

2022-05-06 11:59 UTC, rorshaan commented on app/controllers/attendences_controller.rb
> +    if current_employee.role.name == 'HR'
Add a method to check the role and replace it everywhere where you are checking for HR and other roles

2022-05-06 12:02 UTC, rorshaan requested changes
Test cases are missing.

2022-05-06 13:45 UTC, rorshaan commented on app/controllers/attendences_controller.rb
> +  include ApplicationHelper
Why application helper is added to to controller.
Create a saperate module and include it

2022-05-06 13:47 UTC, rorshaan commented on app/helpers/application_helper.rb
> +  def employee_role
Define it in model and use proper naming convention while defining method names

2022-05-06 13:48 UTC, rorshaan commented on app/controllers/tickets_controller.rb
> +    if employee_role
what is the meaning of employee role?

2022-05-09 10:55 UTC, salvimohan commented on app/controllers/application_controller.rb
> +
why extra line

2022-05-10 07:11 UTC, salvimohan commented on app/views/employees/show.html.erb
> +<% if current_employee == @employee || is_hr? %>
it should be current_employee.is_hr?

2022-05-11 14:23 UTC, salvimohan commented on app/controllers/employees_controller.rb
> +    @designations = Designation.all
we can create a before action and move this three line there

2022-05-11 14:23 UTC, salvimohan commented on app/controllers/leafs_controller.rb
> +               Leaf.where(employee_id: current_employee.id).order('created_at DESC')
We can user current_employee.leaves here

2022-05-13 09:26 UTC, closed without merging