EMS107-HR dont know who apply the leave
rorpyll/Employeemanagementsystem pull request #17
Opened 2022-05-09 09:59 UTC by rorpyll

2022-05-09 10:53 UTC, rorshaan requested changes

2022-05-09 10:53 UTC, rorshaan commented on app/controllers/daily_tasks_controller.rb
> +		if current_employee.role.name == "HR"
Why you are repeating same mistakes. alredy discussed many times to use a common method,

2022-05-09 10:53 UTC, rorshaan commented on app/models/leaf.rb
> +  before_create :total_day
naming convention

2022-05-10 07:08 UTC, salvimohan commented on app/controllers/leafs_controller.rb
> +               Leaf.where(employee_id: current_employee.id).order('created_at DESC')
you should use current_employee.leaves

2022-05-13 09:26 UTC, closed without merging