Hr Attendence Module
rorpyll/Employeemanagementsystem pull request #30
Opened 2022-05-19 10:57 UTC by rorpyll

2022-05-19 11:34 UTC, salvimohan commented on app/controllers/hr/attendences_controller.rb
> +      @attendences = if params[:start_date].blank? && params[:end_date].blank?
move logic in Model

2022-05-19 11:35 UTC, salvimohan commented on app/views/hr/attendences/_attendence.html.erb
> +            <tr>
you can use same partial before you have created

2022-05-19 14:42 UTC, rorshaan requested changes

2022-05-19 14:42 UTC, rorshaan commented on spec/controllers/hr/application_controller_spec.rb
> +  describe 'Only all for Hr' do
typo mistake

2022-05-19 14:42 UTC, rorshaan commented on spec/controllers/hr/application_controller_spec.rb
> +      expect(response.status).to eq(200)
specs is not clear.

2022-05-19 14:42 UTC, rorshaan commented on spec/controllers/hr/application_controller_spec.rb
> +      expect(response.status).to eq(200)
status will not be 200(success)

2022-05-19 14:42 UTC, rorshaan commented on spec/controllers/hr/attendence_controller_spec.rb
> +      expect(response.status).to eq(200)
Expect with instance variable value

2022-05-19 14:42 UTC, rorshaan commented on app/controllers/hr/attendences_controller.rb
> +    def show
If possible dry method by using common mettod for show and show_attendence

2022-05-20 09:50 UTC, rorshaan approved these changes

2022-05-20 09:50 UTC, merged