Api for Employee Controller
rorpyll/Employeemanagementsystem pull request #32
Opened 2022-05-20 11:08 UTC by ror-uday

2022-05-20 13:52 UTC, rorpyll requested changes

2022-05-20 13:52 UTC, rorpyll commented on app/controllers/api/v1/employees_controller.rb
> +        @employee = get_employee
why we need instance variable?

2022-05-20 13:58 UTC, ror-uday commented on app/controllers/api/v1/employees_controller.rb
> +        @employee = get_employee
change

2022-06-04 07:32 UTC, rorpyll commented on app/serializers/v1/employee_serializer.rb
> +    def designation
def designation
        object.designation.name
    end

2022-06-04 07:32 UTC, rorpyll commented on app/serializers/v1/employee_serializer.rb
> +    def designation
def designation
        object.designation.name
    end

2022-07-12 09:46 UTC, ror-uday commented on app/serializers/v1/employee_serializer.rb
> +    def designation
done

2022-07-22 09:57 UTC, closed without merging