Api for Holiday controller
rorpyll/Employeemanagementsystem pull request #36
Opened 2022-05-23 10:31 UTC by ror-uday

2022-05-25 05:40 UTC, rorpyll requested changes

2022-05-25 05:40 UTC, rorpyll commented on spec/v1/holidays_spec.rb
> +  describe 'GET# holidays#index' do
describe statement is not right

2022-05-25 05:40 UTC, rorpyll commented on spec/v1/holidays_spec.rb
> +    it 'index the holidays list' do
it statement is not right

2022-05-25 06:16 UTC, ror-uday commented on spec/v1/holidays_spec.rb
> +  describe 'GET# holidays#index' do
changes done

2022-05-25 06:16 UTC, ror-uday commented on spec/v1/holidays_spec.rb
> +    it 'index the holidays list' do
changes done

2022-05-25 06:18 UTC, rorpyll approved these changes

2022-06-04 07:33 UTC, rorpyll commented on app/controllers/api/v1/holidays_controller.rb
> +      def holiday_params
why?

2022-06-04 07:33 UTC, rorpyll commented on app/controllers/api/v1/holidays_controller.rb
> +      def holiday_params
why?

2022-06-04 07:34 UTC, rorpyll approved these changes

2022-07-22 09:56 UTC, closed without merging