Api for leave controller
rorpyll/Employeemanagementsystem pull request #37
Opened 2022-05-23 10:44 UTC by ror-uday

2022-05-25 10:22 UTC, rorshaan requested changes

2022-05-25 10:22 UTC, rorshaan commented on app/controllers/api/v1/leafs_controller.rb
> +        current_employee
Do we need this line?

2022-05-25 10:22 UTC, rorshaan commented on app/controllers/api/v1/leafs_controller.rb
> +        data = Leaf.new(leaf_params)
You you have used a wrong variable? 'data'
please use proper naming convention

2022-05-25 10:22 UTC, rorshaan commented on app/controllers/api/v1/leafs_controller.rb
> +        data = Leaf.find(params[:id])
naming convention

2022-05-25 10:22 UTC, rorshaan commented on app/serializers/api/v1/leaf_serializer.rb
> +  module V1
Have you run the robocop?

2022-05-25 10:22 UTC, rorshaan commented on spec/v1/leafs_spec.rb
> +      expect(response.status).to eq(200)
Why you are not expecting with objects?

2022-05-25 10:22 UTC, rorshaan commented on spec/v1/leafs_spec.rb
> +
Expect with objects as well in every spec.

2022-05-25 12:57 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +        current_employee
changes done

2022-05-25 12:57 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +        data = Leaf.new(leaf_params)
done sir

2022-05-25 12:57 UTC, ror-uday commented on spec/v1/leafs_spec.rb
> +
changes done

2022-05-25 12:57 UTC, ror-uday commented on app/serializers/api/v1/leaf_serializer.rb
> +  module V1
yes sir

2022-05-27 14:46 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +        leaf_data = Leaf.where(employee_id: current_employee.id).order('created_at DESC')
current_employee.leafs

2022-05-27 14:49 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +          render json: { message: ['leave status not update'] }, status: 304, type: 'failed'
why 304 used

2022-05-27 14:49 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +          render json: { message: ['leave status not update'] }, status: 304, type: 'failed'
why 304 used

2022-05-27 14:49 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +            render json: leaf_data
Add error code

2022-05-27 14:49 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +            render json: leaf_data
Add error code

2022-05-27 14:50 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +        if leaf_data.from_date > Time.now
move in model

2022-05-27 14:51 UTC, ror-uday commented on app/serializers/api/v1/leaf_serializer.rb
> +      attributes :id, :leave_type, :from_date, :till_date, :leave_starts, :leave_end, :total_days, :resion, :leave_status,
change type of column name

2022-05-27 14:51 UTC, ror-uday commented on app/serializers/api/v1/leaf_serializer.rb
> +      attributes :id, :leave_type, :from_date, :till_date, :leave_starts, :leave_end, :total_days, :resion, :leave_status,
change type of column name

2022-05-27 14:53 UTC, ror-uday commented on config/routes.rb
> +      resources :leafs
use only

2022-05-31 08:58 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +        if leaf_data.from_date > Time.now
changes done

2022-05-31 09:17 UTC, ror-uday commented on app/serializers/api/v1/leaf_serializer.rb
> +      attributes :id, :leave_type, :from_date, :till_date, :leave_starts, :leave_end, :total_days, :resion, :leave_status,
changes done

2022-05-31 09:17 UTC, ror-uday commented on app/controllers/api/v1/leafs_controller.rb
> +        if leaf_data.from_date > Time.now
done

2022-06-04 07:44 UTC, rorpyll approved these changes
MSD

2022-07-22 09:56 UTC, closed without merging