Api for Performance Controller
rorpyll/Employeemanagementsystem pull request #41
Opened 2022-05-24 07:39 UTC by ror-uday

2022-05-25 10:55 UTC, rorshaan requested changes

2022-05-25 10:55 UTC, rorshaan commented on config/routes.rb
> +      resources :performances
Why you are using all routes if you have only index action

2022-05-25 10:55 UTC, rorshaan commented on spec/v1/performance_spec.rb
> +      expect(response.status).to eq(200)
Expect with objects

2022-05-25 10:55 UTC, rorshaan commented on app/controllers/api/v1/performances_controller.rb
> +        data = Performance.all
use proper name of variables

2022-05-26 14:36 UTC, ror-uday commented on config/routes.rb
> +      resources :performances
changes done

2022-07-12 13:39 UTC, closed without merging