Add Flash messages
rorpyll/Employeemanagementsystem pull request #43
Opened 2022-05-25 10:39 UTC by rorpyll

2022-05-25 10:57 UTC, rorshaan requested changes

2022-05-25 10:57 UTC, rorshaan commented on app/controllers/attendences_controller.rb
> +    redirect_to root_path, { alert: 'NOT FOUND :)' } unless @attendence.present?
use I18n

2022-05-25 10:57 UTC, rorshaan commented on app/controllers/daily_tasks_controller.rb
> +      redirect_to root_path, { alert: 'You Have Not Access :)' } unless @daily_task.present?
Use I18n

2022-05-25 10:57 UTC, rorshaan commented on app/controllers/daily_tasks_controller.rb
> +    render json: { alert: 'Not Found' }, status: 404 unless @daily_task.present?
Use I18n

2022-05-25 11:25 UTC, rorpyll commented on app/controllers/attendences_controller.rb
> +    redirect_to root_path, { alert: 'NOT FOUND :)' } unless @attendence.present?
Done

2022-05-25 11:25 UTC, rorpyll commented on app/controllers/daily_tasks_controller.rb
> +      redirect_to root_path, { alert: 'You Have Not Access :)' } unless @daily_task.present?
done

2022-05-25 11:26 UTC, rorpyll commented on app/controllers/daily_tasks_controller.rb
> +    render json: { alert: 'Not Found' }, status: 404 unless @daily_task.present?
render json not sport  i18n

2022-05-25 11:29 UTC, rorpyll commented on app/controllers/daily_tasks_controller.rb
> +    render json: { alert: 'Not Found' }, status: 404 unless @daily_task.present?
done with redirect_to

2022-05-26 11:53 UTC, rorshaan approved these changes

2022-05-26 11:53 UTC, merged