Admin holiday
rorpyll/Employeemanagementsystem pull request #60
Opened 2022-06-16 14:59 UTC by Namrata12gupta

2022-06-20 07:01 UTC, rorpyll requested changes

2022-06-20 07:01 UTC, rorpyll commented on spec/controllers/admin_main/holiday_controller_spec.rb
> +    it 'response successfully when holiday exit' do
write spec for not found condition

2022-06-20 07:01 UTC, rorpyll commented on spec/controllers/admin_main/holiday_controller_spec.rb
> +      expect(response.status).to eq(200)
write spec for not found condition

2022-06-20 07:01 UTC, rorpyll commented on spec/controllers/admin_main/holiday_controller_spec.rb
> +  describe '#create' do
write spec for not create condition

2022-06-20 11:25 UTC, ror-uday requested changes

2022-06-20 11:25 UTC, ror-uday commented on spec/controllers/admin_main/holiday_controller_spec.rb
> +  describe '#update' do
write spec for when holiday not update

2022-06-21 12:34 UTC, Namrata12gupta commented on app/controllers/admin_main/holidays_controller.rb
> +      @holiday = Holiday.find(params[:id])
changes done

2022-06-21 14:11 UTC, Namrata12gupta commented on app/views/admin_main/holidays/edit.html.erb
> +    <%= form_with model: @holiday, :url => admin_main_holiday_path, :method => "patch" do |form| %>
changes done

2022-06-21 14:22 UTC, Namrata12gupta commented on app/views/admin_main/holidays/new.html.erb
> +  <main id="main" class="main">
changes done

2022-06-21 14:30 UTC, Namrata12gupta commented on app/views/shared/_header.html.erb
> +         <% if current_employee.role.name == "Employee" || current_employee.role.name == "HR" %>
changes done

2022-06-21 14:37 UTC, Namrata12gupta commented on spec/controllers/admin_main/holiday_controller_spec.rb
> +    it 'response successfully when holiday exit' do
changes done

2022-06-21 14:39 UTC, Namrata12gupta commented on spec/controllers/admin_main/holiday_controller_spec.rb
> +  describe '#update' do
changes done

2022-06-22 06:45 UTC, ror-uday requested changes

2022-06-22 06:45 UTC, ror-uday commented on app/models/ability.rb
> +        if employee.role.name == "HR" || employee.role.name == "Admin"
use instance method

2022-06-23 06:55 UTC, ror-uday approved these changes

2022-06-24 07:21 UTC, chiraggargsass requested changes

2022-06-24 07:21 UTC, chiraggargsass commented on app/views/shared/_header.html.erb
> +
remove blank space

2022-06-24 07:21 UTC, chiraggargsass commented on app/views/shared/_header.html.erb
> +            <%= 'Profile' %>
remove ruby tag

2022-06-24 07:21 UTC, chiraggargsass commented on app/views/shared/_header.html.erb
> +        <% if current_employee.is_admin? %>
should be use OR(||) condition for HR and ADMIN.
not to use same code in both condition.

2022-06-24 07:21 UTC, chiraggargsass commented on app/views/shared/_header.html.erb
> +            <%= 'Profile' %>
Remove Ruby tag

2022-06-24 07:21 UTC, chiraggargsass commented on config/routes.rb
> +        resources :daily_tasks
add proper indentation

2022-07-01 10:04 UTC, Namrata12gupta commented on app/views/shared/_header.html.erb
> +
done

2022-07-01 11:06 UTC, Namrata12gupta commented on app/views/shared/_header.html.erb
> +            <%= 'Profile' %>
done

2022-07-01 11:06 UTC, Namrata12gupta commented on app/views/shared/_header.html.erb
> +        <% if current_employee.is_admin? %>
done

2022-07-01 11:06 UTC, Namrata12gupta commented on config/routes.rb
> +        resources :daily_tasks
done

2022-07-01 11:07 UTC, Namrata12gupta commented on app/views/shared/_header.html.erb
> +            <%= 'Profile' %>
done

2022-07-01 12:16 UTC, ror-uday requested changes

2022-07-01 12:16 UTC, ror-uday commented on app/controllers/admin_main/holidays_controller.rb
> +      redirect_to root_path, { notic: 'NOT FOUND' } unless @holiday.present?
spelling mistake notice

2022-07-01 12:20 UTC, Namrata12gupta commented on app/controllers/admin_main/holidays_controller.rb
> +      redirect_to root_path, { notic: 'NOT FOUND' } unless @holiday.present?
done

2022-07-02 06:52 UTC, chiraggargsass approved these changes

2022-07-07 10:28 UTC, merged