Admin ticket
rorpyll/Employeemanagementsystem pull request #61
Opened 2022-06-16 15:00 UTC by RiyaSantore04

2022-06-20 09:02 UTC, salvimohan commented on app/models/ticket.rb
> +  belongs_to :employee, dependent: :destroy
Don;t add dependent destroywith belongs_tp

2022-06-20 09:02 UTC, salvimohan commented on app/views/admin_main/tickets/index.html.erb
> +        <td><% if ticket.status == 'accept' %>
move logic in helper

2022-06-20 09:04 UTC, salvimohan commented on app/models/comment.rb
> +  belongs_to :ticket
who comments so add association of employee as well

2022-06-20 11:32 UTC, ror-uday requested changes

2022-06-20 11:32 UTC, ror-uday commented on app/controllers/admin_main/tickets_controller.rb
> +	  	@ticket = Ticket.find(params[:id])
correct indentation

2022-06-20 11:32 UTC, ror-uday commented on app/models/ability.rb
> +        if employee.role.name == "HR" ||  employee.role.name == "Admin"
why are you not using instance method?

2022-06-20 11:32 UTC, ror-uday commented on app/views/admin_main/tickets/index.html.erb
> +
remove uncessary space and correct the alignment of code

2022-06-20 11:40 UTC, ror-uday requested changes

2022-06-20 11:40 UTC, ror-uday commented on app/controllers/admin_main/tickets_controller.rb
> +	    if current_user.role.name == 'Admin'
why are you not using instance method?

2022-06-20 11:40 UTC, ror-uday commented on app/views/admin_main/tickets/edit.html.erb
> +
correct indentation

2022-06-20 14:51 UTC, RiyaSantore04 commented on app/controllers/admin_main/comments_controller.rb
> +	    @comment = Comment.new( commenter: params[:commenter], ticket_id: params[:ticket_id])
Changes Done

2022-06-20 14:51 UTC, RiyaSantore04 commented on app/models/ticket.rb
> +  belongs_to :employee, dependent: :destroy
Changes Done

2022-06-20 14:52 UTC, RiyaSantore04 commented on app/models/comment.rb
> +  belongs_to :ticket
Changes Done

2022-06-20 14:52 UTC, RiyaSantore04 commented on app/controllers/admin_main/tickets_controller.rb
> +	      @tickets = Ticket.order(created_at: :desc)
Changes Done

2022-06-20 14:52 UTC, RiyaSantore04 commented on app/controllers/admin_main/tickets_controller.rb
> +	  	@ticket = Ticket.find(params[:id])
Changes Done

2022-06-20 14:52 UTC, RiyaSantore04 commented on app/models/ability.rb
> +        if employee.role.name == "HR" ||  employee.role.name == "Admin"
Changes Done

2022-06-20 14:52 UTC, RiyaSantore04 commented on app/views/admin_main/tickets/index.html.erb
> +
Changes Done

2022-06-20 14:52 UTC, RiyaSantore04 commented on app/views/admin_main/tickets/edit.html.erb
> +
Changes Done

2022-06-21 06:26 UTC, rorpyll requested changes

2022-06-21 09:52 UTC, RiyaSantore04 commented on app/controllers/admin_main/tickets_controller.rb
> +	      @tickets = Ticket.where(employee_id: current_employee)
Changes Done

2022-06-21 09:52 UTC, RiyaSantore04 commented on app/views/admin_main/tickets/index.html.erb
> +        <% else %>
Changes Done

2022-06-24 08:03 UTC, chiraggargsass requested changes

2022-06-24 08:03 UTC, chiraggargsass commented on config/routes.rb
> +  # ActiveAdmin.routes(self)
remove comments

2022-06-27 14:38 UTC, RiyaSantore04 commented on config/routes.rb
> +  # ActiveAdmin.routes(self)
Changes done

2022-06-27 14:40 UTC, RiyaSantore04 commented on app/views/shared/_header.html.erb
> +          <%= 'Profile' %>
Changes done

2022-06-27 14:41 UTC, RiyaSantore04 commented on app/views/tickets/index.html.erb
> +
changes done

2022-07-04 13:08 UTC, closed without merging