Admin Employee and rspec
rorpyll/Employeemanagementsystem pull request #63
Opened 2022-06-17 11:45 UTC by Namrata12gupta

2022-06-20 09:49 UTC, rorpyll requested changes

2022-06-20 09:49 UTC, rorpyll commented on app/controllers/admin_main/employees_controller.rb
> +      @designations = Designation.all
use class method for similar code

2022-06-20 09:49 UTC, rorpyll commented on app/controllers/admin_main/employees_controller.rb
> +      @employee = Employee.find_by_id params[:id]
use class method for similar code

2022-06-20 11:19 UTC, ror-uday requested changes

2022-06-20 11:19 UTC, ror-uday commented on app/views/shared/_header.html.erb
> +          <% else %>
correct indentation

2022-06-20 11:19 UTC, ror-uday commented on config/routes.rb
> +  namespace :admin_main do
use rubocop

2022-06-21 09:46 UTC, Namrata12gupta commented on app/controllers/admin_main/employees_controller.rb
> +      @designations = Designation.all
Changes Done

2022-06-21 09:47 UTC, Namrata12gupta commented on app/controllers/admin_main/employees_controller.rb
> +      @employee = Employee.find_by_id params[:id]
Changes Done

2022-06-21 09:47 UTC, Namrata12gupta commented on app/views/shared/_header.html.erb
> +          <% unless current_employee.role.name == "HR" ||current_employee.role.name == "Admin" %>
Changes Done

2022-06-21 11:08 UTC, rorpyll requested changes

2022-06-21 11:08 UTC, rorpyll commented on app/models/ability.rb
> +        if employee.role.name == "HR" || employee.role.name == "Admin"
why are you not use instance method

2022-06-21 11:08 UTC, rorpyll commented on spec/controllers/admin_main/employee_controller_spec.rb
> +      expect(response.status).to eq(302)
conspire with object like employee count  2 after destroy employee count should be 1

2022-06-22 06:00 UTC, rorpyll approved these changes

2022-06-22 06:41 UTC, ror-uday approved these changes

2022-06-22 08:47 UTC, salvimohan commented on app/controllers/admin_main/employees_controller.rb
> +      set_designations
create filter for it

2022-06-22 08:49 UTC, salvimohan commented on app/views/employees/index.html.erb
> +                    <td><% if current_employee.is_admin? %>
<% if current_employee.is_admin? %>
 <td>  <%= link_to 'Edit', edit_admin_main_employee_path(employee), class: "btn btn-primary"%></td>
 <td><%= link_to 'Destroy', admin_main_employee_path(employee),method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"%>     </td>
 <% end %>

2022-06-22 08:50 UTC, salvimohan commented on app/views/shared/_header.html.erb
> +        <%= "Dashboard" %>
why

2022-07-02 06:27 UTC, merged